DEFAULT_FOLDER = crkbd/rev1/common
#BOOTLOADER = atmel-dfu
OLED_DRIVER_ENABLE = yes
NO_USB_STARTUP_CHECK = yes
WAIT_FOR_USB = no
RGBLIGHT_ENABLE = yes
LTO_ENABLE = yes

AUTO_SHIFT_ENABLE = no
EXTRAKEY_ENABLE = no

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
COMBO_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
RAW_ENABLE = no
